config/routes.rb
Rails.application.routes.draw do
  
  # Subscriber  
  get 'subscribers/new'
  post 'subscribers', to: "subscribers#create"
  match 'subscribers/all/edit' => 'subscribers#edit_all', as: :edit_all, via: :get
  match 'subscribers/all' => 'subscribers#update_all' , as: :update_all, via: :patch

  # Presenter
  get 'presenters/new'
  post 'presenters', to: "presenters#create"
  get 'presenters/update'

  get 'presenters/delete'
  
  # Workshop

  get 'workshops/admin_home'
  get 'workshops/show_single_record'
  resources :workshops
  
  
  
  root to: 'workshops#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/college.rb
class College < ApplicationRecord
	has_many :departments
end

app/models/department.rb
class Department < ApplicationRecord
	belongs_to :college
  	has_many :subscribers
end

app/models/presenter.rb
class Presenter < ApplicationRecord
	has_and_belongs_to_many :workshops
	attr_accessor :for_edit, :workshop_id    
end

app/models/subscriber.rb
class Subscriber < ApplicationRecord
	belongs_to :department
	has_and_belongs_to_many :workshops
	attr_accessor :work_id
end

app/models/workshop.rb
class Workshop < ApplicationRecord
	has_and_belongs_to_many :subscribers
	has_and_belongs_to_many :presenters
    validates_presence_of :title, :goals, :skills
    accepts_nested_attributes_for :presenters
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :set_locale
  
  
  def default_url_options
  { locale: I18n.locale }
  end
  def set_locale
        I18n.locale = params[:locale] || I18n.default_locale
    end
end

app/controllers/presenters_controller.rb
class PresentersController < ApplicationController
    
    before_action :init
    
  def init
        @for_edit = false
        @workshop_id = -1
  end
  
  
  def new
      @presenter = Presenter.new
      @for_edit = params[:for_edit]
      @workshop_id = params[:workshop_id]
       
  end

  def create
      @presenter = Presenter.new(secure_params)
      if @presenter.save
         
          if params[:presenter][:for_edit] == "true"
              redirect_to edit_workshop_path(params[:presenter][:workshop_id])
          else
              redirect_to new_workshop_path
          end
          
      else
          render action: 'new'
      end
  end
  def update
  end

  def delete
  end
  
  private
  def secure_params
      params.require(:presenter).permit(:name,:position, :workshop_id, :for_edit)
  end
end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController
  def new
      @subscriber = Subscriber.new
      @departments = Department.all
  end
  
  def create
      @subscriber = Subscriber.new(secure_params)
      @workshop = Workshop.find(@subscriber.work_id)
      @subscriber.workshops << @workshop
      if @subscriber.save        
          flash[:notice] = "You have registered"
          redirect_to root_path
      else
          render action: "new"
      end
  end
  
  def edit_all
      @subscribers = Subscriber.includes(:workshops).where(workshops: { id: params[:id] })
  end
  
  def update_all
          
      
      params[:subscriber].keys.each do |id|
          @subscriber = Subscriber.find(id.to_i)
          @subscriber.update_attributes(edit_secure_params(id))
      end
      
      redirect_to workshops_admin_home_path
  end
  
  private
  
  def secure_params
        params.require(:subscriber).permit(:title,:name,:position,:email,:phone,:department_id, :work_id, {workshop_ids: []})
  end
  
  def edit_secure_params(id)
     params[:subscriber][id].permit(:attend)
  end
end

app/controllers/workshops_controller.rb
class WorkshopsController < ApplicationController
    
    
    helper_method :sort_column, :sort_direction
    
  def new
      @workshop = Workshop.new
  end
  
  def create
      @workshop = Workshop.new(secure_params)
     
      var = params[:workshop][:current]
      if var == "true"
          
          @workshop.upcoming = "f"
      else
          @workshop.upcoming = "t"
      end
      if @workshop.save
          redirect_to workshops_admin_home_path
      else
          render action: 'new'
      end
  end 
  
  def show
    @workshop = Workshop.find(params[:id])
  end

  def edit
    @workshop = Workshop.find(params[:id])
  end
  
  def update
      @workshop = Workshop.find(params[:id])
       var = params[:workshop][:current]
      if var == "true"
          
          @workshop.upcoming = "f"
      else
          @workshop.upcoming = "t"
      end
      if @workshop.update_attributes(secure_params)
        redirect_to workshops_admin_home_path
      else
        render 'edit'
      end
    end

  def destroy
      @workshop = Workshop.find(params[:id]).destroy
      
      redirect_to workshops_admin_home_path
  end
  
  def home
      session[:admin] = false
      Workshop.all
      move_to_past
      @upcoming_workshops = Workshop.where(upcoming: true).order(sort_column+ " " + sort_direction)
      @current_workshops = Workshop.where(current: true).order(sort_column+ " " + sort_direction)
      @past_workshops = Workshop.where(current: false, upcoming: false).order(sort_column+ " " + sort_direction)
  end
  
  def admin_home
      
      session[:admin] = true
      Workshop.all
      move_to_past
      @upcoming_workshops = Workshop.where(upcoming: true).order(sort_column+ " " + sort_direction)
      @current_workshops = Workshop.where(current: true).order(sort_column+ " " + sort_direction)
      @past_workshops = Workshop.where(current: false, upcoming: false).order(sort_column+ " " + sort_direction)
	
  end
  
  
  def show_single_record
      @workshop = Workshop.find(params[:id])
      @show_single_record_admin = params[:show_single_record_admin]
      
  end
  
  private
  
    
    
    def secure_params
        params.require(:workshop).permit(:title,:date,:goals,:skills, :current, :upcoming , {presenter_ids: []})
    end
     def sort_column
        Workshop.column_names.include?(params[:sort]) ? params[:sort] : "id"
     end
  
     def sort_direction
        %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
     end
     def move_to_past
	@workshops = Workshop.all
	@workshops.each do |workshop|
		_date = workshop.date
		if _date < Date.today
		   workshop.upcoming = "f"
		   workshop.current = "f"
		   workshop.save
		end		
	end
     end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/presenters_helper.rb
module PresentersHelper
end

app/helpers/subscribers_helper.rb
module SubscribersHelper
end

app/helpers/workshops_helper.rb
module WorkshopsHelper
    def sortable(column, title = nil)
        title ||= column.titleize
        column == sort_column ? "current #{sort_direction}" : nil
        direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
        link_to title, {:sort => column, :direction => direction}#, {:class => css_class}
    end

end

app/views/layouts/_messages.html.slim
- # Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    |  <div class="alert alert-dismissible alert-
    = name.to_s == 'notice' ? 'success' : 'danger'
    | "> 
    button.close[type="button" data-dismiss="alert" aria-hidden="true"]
      | ×
    = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.slim
- # navigation styled for Bootstrap 3.0
nav.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      button.navbar-toggle[type="button" data-toggle="collapse" data-target=".navbar-collapse"]
        span.sr-only
          | Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to simple_format(t(:home)), root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      ul.nav.navbar-nav
        = render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.slim
- # add navigation links to this file
- if session[:admin]
    li
        =link_to t(:add_workshop), new_workshop_path
    li
        =link_to t(:stat)
    li
        =link_to t(:add_user)
- else
    li
        =link_to t(:admin_login), workshops_admin_home_path
         
li
    =link_to t(:lang), url_for( :locale => t(:lang_template) )

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : "Survey Monkey"
    |  <meta name="description" content="
    = content_for?(:description) ? yield(:description) : "Survey Monkey"
    | "> 
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track' => 'reload'
    = csrf_meta_tags
  body
    header
      = render 'layouts/navigation'
    main[role="main"]
      = render 'layouts/messages'
      = yield

app/views/presenters/_error_messages.html.slim
- if @presenter.errors.any?
  #error_explanation
    .alert.alert-danger
      |  The form contains 
      = pluralize(@presenter.errors.count, "error")
      | . 
    ul
      - @presenter.errors.full_messages.each do |msg|
        li
          = msg

app/views/presenters/_new.html.slim
  div class="modal-dialog modal-content modal-body"
    = simple_form_for @presenter, remote: true do |form|
      = render 'error_messages'
      = form.input :name, label: "Presenter's Name", class: 'form-control'
      = form.input :position, label: "Presenter's Position"
      = form.input :for_edit, as: :hidden, input_html: {value: @for_edit}
      = form.input :workshop_id, as: :hidden, input_html: {value: @workshop_id}
      = form.button :submit,'Submit', class: 'submit', id: "add-item"

app/views/presenters/delete.html.slim
h1
  | Presenters#delete
p
  | Find me in app/views/presenters/delete.html.erb

app/views/presenters/new.js.slim
| $("#workshops-modal").html("#{j render 'new'}")

app/views/presenters/update.html.slim
h1
  | Presenters#update
p
  | Find me in app/views/presenters/update.html.erb

app/views/subscribers/edit_all.html.slim
= simple_form_for :subscriber, :url => update_all_path, html: {method: :patch} do |form|
  .table-responsive
    table.table
      thead
        tr
          th.col-xs-8= "name"
          th="position"
          th= "attend"
        - @subscribers.each do |subscriber|
          = simple_fields_for "subscriber[]", subscriber do |subscriber_fields|
            tbody
              tr
                td= subscriber_fields.input :name, label: false
                td= subscriber_fields.input :position, label: false
                td= subscriber_fields.input :attend , as: :boolean , label: false
        = form.button :submit, 'Save', class: 'btn btn-primary'

app/views/subscribers/new.html.slim
div class="modal-dialog modal-content modal-body"
  = simple_form_for @subscriber do |form|
    = form.input :title, collection: [t(:Mr),t(:Ms),t(:Mrs),t(:Prof),t(:Eng),t(:Dr)]
    = form.input :name
    = form.input :position , collection: [t(:Ta), t(:Le),t(:Ap),t(:Asp),t(:Prof),t(:Other)]
    = form.input :email
    = form.input :phone
    = form.input :department_id, label: 'Colleges/Departments' ,as: :grouped_select, collection: College.all, group_method: :departments,  prompt: "Select One" 
    = form.input :work_id , as: :hidden, input_html: {value: params[:id]}
    = form.button :submit,'Submit', class: 'btn btn-primary', id: "add-item"
    = link_to 'Cancel', workshops_admin_home_path,class: 'btn btn-default', remote: true

app/views/workshops/_admin_table.html.slim
.table-responsive
  table.table
    thead
      tr
        th.col-xs-8= sortable "title"
        th= sortable "date"
    tbody
      - locals[:workshop].each do |workshop|
        tr
          td= link_to workshop.title, workshops_show_single_record_path(id: workshop.id, show_single_record_admin: true), remote: true
          td= workshop.date

app/views/workshops/_error_messages.html.slim
- if @workshop.errors.any?
  #error_explanation
    .alert.alert-danger
      |  The form contains 
      = pluralize(@workshop.errors.count, "error")
      | . 
    ul
      - @workshop.errors.full_messages.each do |msg|
        li
          = msg

app/views/workshops/_show_single_record.html.slim
#general-form.modal-dialog.modal-content.modal-body
  = simple_format(@workshop.title)
  = @workshop.date
  = simple_format("<h4>Goals: </h4>" + @workshop.goals)
  = simple_format("<h4>Skills: </h4>" + @workshop.skills)
  - if !@workshop.presenters.empty?
    = simple_format("<h4> Presenters: </h4>") 
    - @workshop.presenters.each do |x|
      = simple_format(x.name + " -  " + x.position)
  - isCurrent = @workshop.current
  - if (isCurrent == true and !@show_single_record_admin)
   = link_to  subscribers_new_path(:id=>@workshop.id), class: 'btn btn-primary' do
    i.glyphicon.glyphicon-pencil
    |  Register 
  - if (@show_single_record_admin)
   = link_to  edit_workshop_path(:id=>@workshop.id), class: 'btn btn-success' do
     i.glyphicon.glyphicon-plus
     |  Update
   = " "
   = link_to workshop_path(@workshop) , method: :delete,  class: 'btn btn-danger' do
     i class="glyphicon glyphicon-minus"
     |  Delete
   = " "
   = link_to edit_all_path(id: @workshop.id), class: 'btn btn-primary' do
     i.glyphicon.glyphicon-list
     | Attendance
	    

app/views/workshops/_table.html.slim
.table-responsive
  table.table
    thead
      tr
        th.col-xs-8= sortable "title"
        th= sortable "date"
    tbody
      - locals[:workshop].each do |workshop|
        tr
          td= link_to workshop.title, workshops_show_single_record_path(id: workshop.id), remote: true
          td= workshop.date

app/views/workshops/admin_home.html.slim
h3
  |
    Current Workshops
= render "admin_table", locals: {workshop: @current_workshops}

h3
  |
    Upcoming Workshops
= render "admin_table", locals: {workshop: @upcoming_workshops}    

h3
  |
    Past Workshops
= render "admin_table", locals: {workshop: @past_workshops}       
// showing the details 
div id="show_single_record_modal"

app/views/workshops/delete.html.slim
h1
  | Workshops#delete
p
  | Find me in app/views/workshops/delete.html.erb

app/views/workshops/edit.html.slim
div id="workshops-modal"
div id="general-form" class="modal-dialog modal-content modal-body"
  = simple_form_for @workshop do |form|
    = render 'error_messages'
    = form.input :title, class: 'form-control'
    = form.input :date
    = form.association :presenters, as: :select
    = link_to "Add new Presenter" , presenters_new_path(workshop_id: @workshop.id, for_edit: true), remote: true
    = form.input :goals, as: :text
    = form.input :skills, as: :text
    = form.collection_radio_buttons :current, 
        [[true, 'Current'], [false, 'Upcoming']], 
          :first, 
          :last,
          :item_wrapper_class => 'inline'
    = simple_format(" ")
    = form.button :submit,'Update', class: 'submit'

app/views/workshops/home.html.slim
h3
  |
    Current Workshops
= render "table", locals: {workshop: @current_workshops}

h3
  |
    Upcoming Workshops
= render "table", locals: {workshop: @upcoming_workshops}    

h3
  |
    Past Workshops
= render "table", locals: {workshop: @past_workshops}       
div id="show_single_record_modal"

app/views/workshops/new.html.slim
div id="workshops-modal"
div id="general-form" class="modal-dialog modal-content modal-body"
  = simple_form_for @workshop, remote: true do |form|
    = render 'error_messages'
    = form.input :title, class: 'form-control'
    = form.input :date
    = form.association :presenters, collection: Presenter.order(id: :desc)
    = form.simple_fields_for :presenters do |p|
      = p.input :name
      = p.input :position
    = link_to "Add new Presenter" , presenters_new_path, remote: true
    = form.input :goals, as: :text
    = form.input :skills, as: :text
    = form.collection_radio_buttons :current, 
        [[true, 'Current'], [false, 'Upcoming']], 
          :first, 
          :last,
          :item_wrapper_class => 'inline',
          :checked => true
    = simple_format(" ")
    = form.button :submit,'Submit', class: 'btn btn-primary', id: "add-item"
    = link_to 'Cancel', workshops_admin_home_path,class: 'btn btn-default', remote: true
         

app/views/workshops/show_single_record.js.slim
| $("#show_single_record_modal").html("#{j render 'show_single_record'}") 

app/views/workshops/update.html.slim
h1
  | Workshops#update
p
  | Find me in app/views/workshops/update.html.erb